-- Local `supabase db reset` runs this file after migrations.
-- Dev auth users (admin + test) are created via GoTrue Admin API in
-- `scripts/seed-dev-test-user.mjs` (see `npm run reset`).
-- Tour/blog fixtures: `supabase/seed-data.sql` (run after dev users exist).
